--회원가입
DROP TABLE MEMBER purge;
CREATE TABLE MEMBER(
		SEQ  					NUMBER,
		ID 						VARCHAR2(20) PRIMARY KEY,
		PW 						VARCHAR2(15),
		NAME 					VARCHAR2(20),
		JUMIN1 				NUMBER,
		JUMIN2 				NUMBER,
		EMAIL1 				VARCHAR2(25),
		EMAIL2					VARCHAR2(25),
		EMAIL_GET 			VARCHAR2(7),
		MOBILE 				VARCHAR2(13),
		PHONE 					VARCHAR2(13),
		ZIPCODE1 			VARCHAR2(13),
		ZIPCODE2				VARCHAR2(13),
		ADDR1 					VARCHAR2(70),
		ADDR2 					VARCHAR2(70),
		MEMBER_DATE 		DATE
);

--주소 
DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE (
	  ID 					NUMBER  PRIMARY KEY,
	  ZIPCODE 		VARCHAR2(7),
	  SIDO 				VARCHAR2(10),
	  GUGUN 			VARCHAR2(30),
	  DONG 			VARCHAR2(36),
	  RI 					VARCHAR2(60),
	  BUNJI 			VARCHAR2(50)
);

select * from MEMBER;
select * from ZIPCODE;



--레시피
DROP TABLE RECIPE PURGE;
CREATE TABLE RECIPE(
		SEQ  					NUMBER,
		FOOD_NAME  		VARCHAR2(20),
		IMAGE					VARCHAR2(10000),
		CONTENT	  			VARCHAR2(10000),
		RECIPE_DATE		DATE,
		
		
);

SELECT * FROM RECIPE;

--상품 등록
DROP TABLE GOODS PURGE;
CREATE TABLE GOODS(
		SEQ  				NUMBER PRIMARY KEY,
		CATEGORY 		VARCHAR2(20),
		NAME 				VARCHAR2(50),
		CONTENT 			VARCHAR2(3000),
		AMOUNT 			NUMBER,
		PRICE 				NUMBER,
		IMAGE 				VARCHAR2(50),
		BEST 				NUMBER,
		STAR					NUMBER,
		REVIEW			VARCHAR2(50),
		REVIEW_SEQ		NUMBER,
		REVIEW_LEV			NUMBER,
		REVIEW_REF			NUMBER,
		GOODS_DATE 		DATE 
		
	);

SELECT * FROM GOODS;

--장바구니
DROP TABLE BASKET PURGE;
CREATE TABLE BASKET(
		SEQ  								NUMBER PRIMARY KEY,
		BASKET_IMAGE	 				VARCHAR2(20),
		BASKET_GOODS_NAME 	VARCHAR2(30),
		BASKET_AMOUNT 			NUMBER,
		BASKET_PRICE					NUMBER,
		BASKET_DATE 					DATE
		
	);

SELECT * FROM BASKET;

--회원 주문관리
DROP TABLE GOODS_ORDER PURGE;
CREATE TABLE GOODS_ORDER(
		SEQ  							NUMBER,
		ORDER_NUMBER			VARCHAR2(20),
		NAME							VARCHAR2(30),
		PAYSTYLE						VARCHAR2(30),
		PAY								NUMBER,
		STAY								VARCHAR2(15),
		ORDER_DATE				DATE 
	);

SELECT * FROM GOODS_ORDER;

--관리자 주문관리
DROP TABLE ADMIN_ORDER PURGE;
CREATE TABLE ADMIN_ORDER(
		SEQ  							NUMBER,
		ORDER_NUMBER			VARCHAR2(20),
		NAME							VARCHAR2(30),
		PAYSTYLE						VARCHAR2(30),
		PAY								NUMBER,
		STAY								VARCHAR2(15),
		ORDER_DATE				DATE 
	);

--커뮤니티
DROP TABLE COMMUNITY PURGE;
CREATE TABLE COMMUNITY (
		SEQ  							NUMBER 	PRIMARY KEY,
		CATEGORY					VARCHAR2(15),
		SUBJECT  						VARCHAR2(20),
		FILE								VARCHAR2(50),
		CONTENT	  					VARCHAR2(10000),
		COMMUNITY_DATE		DATE
	
);

SELECT * FROM COMMUNITY;


--1:1 문의
DROP TABLE QAA PURGE;
CREATE TABLE QAA(
	SEQ  NUMBER,
	
	
);

SELECT * FROM QAA;

--자주하는 질문 
DROP TABLE FAQ PURGE;
CREATE TABLE FAQ(
	SEQ  NUMBER,
);

SELECT * FROM FAQ;
















-----------------------------------------------------------


--GOODS_SEQ는 수정 삭제를 위해 필요

-- 마이 바티스 목록기능 회원 
SELECT G.SEQ AS G_SEQ, G.NAME AS G_NAME, G.PRICE, G.IMAGE, M.SEQ AS M_SEQ, M.ID, M.NAME AS M_NAME, B.AMOUNT   
FROM BASKET B
JOIN MEMBER M ON M.SEQ = B.MEMBER_SEQ
JOIN GOODS G ON G.SEQ = B.GOODS_SEQ


----------------------------------------------------------------------------------





-----------------------------------------------------------


--GOODS_SEQ는 수정 삭제를 위해 필요

-- 마이 바티스 목록기능 회원 
SELECT G.SEQ AS G_SEQ, G.NAME AS G_NAME, G.PRICE, G.IMAGE, M.SEQ AS M_SEQ, M.ID, M.NAME AS M_NAME, B.AMOUNT   
FROM BASKET B
JOIN MEMBER M ON M.SEQ = B.MEMBER_SEQ
JOIN GOODS G ON G.SEQ = B.GOODS_SEQ


----------------------------------------------------------------------------------

DROP SEQUENCE GOODS_SEQ

SELECT GOODS_SEQ.CURRVAL FROM DUAL;



DROP TABLE BASKET;
DROP TABLE GOODS;
DROP TABLE MEMBER;



-- 장바구니
CREATE TABLE BASKET
(
    MEMBER_SEQ NUMBER, --회원 seq
    GOODS_SEQ NUMBER,  --상품 seq
    AMOUNT    NUMBER, -- 장바구니에 담을 수량
    REG_DATE  DATE, -- 장바구니에 담긴 일자
    PRIMARY KEY (MEMBER_SEQ, GOODS_SEQ) -- 회원 seq,상품 seq는 고유값으로 지정
);



 
-- 해당 시퀀스의 현재값
-- SELECT testSeq.CURRVAL FROM DUAL; 

 -- 해당 시퀀스의 다음값
-- SELECT testSeq.NEXTVAL FROM DUAL; 
*여기서 주의할점은 SELECT 하는 조회에서도 NEXTVAL를 썼을경우 시퀀스자체의 값을 실제로 증가시키기 때문에 당황하지말자.


CREATE SEQUENCE GOODS_SEQ;
SELECT GOODS_SEQ.NEXTVAL FROM DUAL;




--1번 회원
INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(1,2,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(1,3,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(1,4,3,SYSDATE);
--2번 회원
INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(2,2,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(2,3,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(2,4,3,SYSDATE);

--3번 회원
INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(3,2,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(3,3,3,SYSDATE);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(3,4,3,SYSDATE);

SELECT * FROM BASKET

-- 상품
CREATE TABLE GOODS
(
    SEQ        NUMBER PRIMARY KEY, -- 상품 seq
    CATEGORY   VARCHAR2(20), 
    NAME       VARCHAR2(50), -- 상품명
    CONTENT    VARCHAR2(3000),
    AMOUNT     VARCHAR2(20),
    PRICE      VARCHAR2(20), -- 가격
    IMAGE      VARCHAR2(50), -- 사진
    BEST       NUMBER,
    STAR       NUMBER,
    REVIEW     VARCHAR2(50),
    REVIEW_SEQ NUMBER,
    REVIEW_LEV NUMBER,
    REVIEW_REF NUMBER,
    GOODS_DATE DATE DEFAULT SYSDATE
);

INSERT INTO GOODS (SEQ, CATEGORY, NAME, CONTENT, AMOUNT, PRICE, IMAGE)
VALUES(GOODS_SEQ.NEXTVAL, '유제품', '치즈', '맛있는치즈', '100', '1200', 'cheese.jpg');

INSERT INTO GOODS (SEQ, CATEGORY, NAME, CONTENT, AMOUNT, PRICE, IMAGE)
VALUES(GOODS_SEQ.NEXTVAL, '과자', '치즈볼과자', '맛있는과자', '100', '1500', 'cheese.jpg');

INSERT INTO GOODS (SEQ, CATEGORY, NAME, CONTENT, AMOUNT, PRICE, IMAGE)
VALUES(GOODS_SEQ.NEXTVAL, '음료', '핫초코', '맛있는 핫초코', '100', '2000', 'cheese.jpg');

SELECT * FROM GOODS


-- 회원
CREATE TABLE MEMBER
(
    SEQ         NUMBER, -- 회원 seq
    ID          VARCHAR2(20) PRIMARY KEY, -- 회원 아이디
    PW          VARCHAR2(15),
    NAME        VARCHAR2(20), -- 회원 이름
    JUMIN1      NUMBER,
    JUMIN2      NUMBER,
    EMAIL1      VARCHAR2(25),
    EMAIL2      VARCHAR2(25),
    EMAIL_GET   VARCHAR2(7),
    MOBILE      VARCHAR2(13),
    PHONE       VARCHAR2(13),
    ZIPCODE1    VARCHAR2(13),
    ZIPCODE2    VARCHAR2(13),
    ADDR1       VARCHAR2(70),
    ADDR2       VARCHAR2(70),
    MEMBER_DATE DATE
);


INSERT INTO MEMBER (SEQ, ID, PW, NAME)
VALUES(1,'aa','aa','나희');

INSERT INTO MEMBER (SEQ, ID, PW, NAME)
VALUES(2,'bb','bb','나라');

INSERT INTO MEMBER (SEQ, ID, PW, NAME)
VALUES(3,'cc','cc','나진');

INSERT INTO MEMBER (SEQ, ID, PW, NAME)
VALUES(4,'admin','dd','관리자');

SELECT * FROM MEMBER





--------------------------------------------------------------------------------------------------------------------------------------


INSERT INTO GOODS (SEQ, CATEGORY, NAME, CONTENT, AMOUNT, PRICE, IMAGE, STAR)
VALUES(GOODS_SEQ.NEXTVAL, '라면', '신라면', '맛있는신라면', '10', '1200', 'image.jpg', 2);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(2,31,3,SYSDATE);

COMMIT;











UPDATE BASKET SET AMOUNT = #{amount}
WHERE GOODS_SEQ = #{goodsSeq} AND MEMBER_SEQ = #{memberSeq}

SELECT COUNT(*) FROM BASKET WHERE MEMBER_SEQ = 2 AND GOODS_SEQ = 30;

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE) 
VALUES (#{memberSeq},#{goodsSeq},#{amount},SYSDATE)

DELETE FROM BASKET WHERE GOODS_SEQ = #{goodsSeq} AND MEMBER_SEQ = #{memberSeq}

CREATE TABLE GOODS
(
    SEQ        NUMBER PRIMARY KEY,
    CATEGORY   VARCHAR2(20),
    NAME       VARCHAR2(50),
    CONTENT    VARCHAR2(3000),
    AMOUNT     VARCHAR2(20),
    PRICE      VARCHAR2(20),
    IMAGE      VARCHAR2(50),
    BEST       NUMBER,
    STAR       NUMBER,
    REVIEW     VARCHAR2(50),
    REVIEW_SEQ NUMBER,
    REVIEW_LEV NUMBER,
    REVIEW_REF NUMBER,
    GOODS_DATE DATE DEFAULT SYSDATE
);

INSERT INTO GOODS (SEQ, CATEGORY, NAME, CONTENT, AMOUNT, PRICE, IMAGE, STAR)
VALUES(GOODS_SEQ.NEXTVAL, '라면', '신라면', '맛있는신라면', '10', '1200', 'image.jpg', 2);

INSERT INTO BASKET(MEMBER_SEQ,GOODS_SEQ,AMOUNT,REG_DATE)
VALUES(2,31,3,SYSDATE);

COMMIT;

--회원
CREATE TABLE MEMBER
(
    SEQ         NUMBER,
    ID          VARCHAR2(20) PRIMARY KEY,
    PW          VARCHAR2(15),
    NAME        VARCHAR2(20),
    JUMIN1      NUMBER,
    JUMIN2      NUMBER,
    EMAIL1      VARCHAR2(25),
    EMAIL2      VARCHAR2(25),
    EMAIL_GET   VARCHAR2(7),
    MOBILE      VARCHAR2(13),
    PHONE       VARCHAR2(13),
    ZIPCODE1    VARCHAR2(13),
    ZIPCODE2    VARCHAR2(13),
    ADDR1       VARCHAR2(70),
    ADDR2       VARCHAR2(70),
    MEMBER_DATE DATE
);







--회원
SELECT G.SEQ AS GOODS_SEQ, B.AMOUNT, G.NAME AS GOODS_NAME, G.IMAGE, G.PRICE, M.NAME AS MEMBER_NAME
FROM BASKET B
JOIN GOODS G ON B.GOODS_SEQ = G.SEQ
JOIN MEMBER M ON B.MEMBER_SEQ = M.SEQ
WHERE B.MEMBER_SEQ = 1

--관리자
SELECT B.AMOUNT, G.NAME, G.IMAGE, G.PRICE, M.NAME
FROM BASKET B
JOIN GOODS G ON B.GOODS_SEQ = G.SEQ
JOIN MEMBER M ON B.MEMBER_SEQ = M.SEQ



















--주문
CREATE TABLE GOODS_ORDER(
   ORDER_NUM NUMBER, -- 주문번호
   ORDER_GOODS_NUM   NUMBER, -- 상품 SEQ
   ORDER_GOODS_NAME VARCHAR2(50), -- 상품 이름
   ORDER_GOODS_AMOUNT NUMBER, -- 상품 전체양
   ORDER_GOODS_IMAGE VARCHAR2(50), -- 상품 이미지
   ORDER_GOODS_PRICE NUMBER, -- 상품 가격
   ORDER_GOODS_COUNT NUMBER, -- 상품 주문 개수
   ORDER_MEMBER_ID VARCHAR2(20), -- 회원 아이디
   ORDER_RECEIVE_NAME VARCHAR2(20),  -- 받는 사람이름
   ORDER_RECEIVE_ADDR1 VARCHAR2(70), -- 배송지
   ORDER_RECEIVE_ADDR2 VARCHAR2(70), -- 배송지
   ORDER_RECEIVE_PHONE VARCHAR2(13), 
   ORDER_RECEIVE_MOBILE VARCHAR2(13), -- 회원 핸드폰 전화
   ORDER_MEMO VARCHAR2(3000), -- 메모
   ORDER_SUM_MONEY NUMBER, -- 주문 총 가격
   ORDER_TRADE_TYPE VARCHAR2(20), --배송 타입
   ORDER_TRADE_DATE DATE DEFAULT SYSDATE, -- 배송 날짜
   ORDER_TRADE_PAYER VARCHAR2(20), -- 결제 타입
   ORDER_DATE DATE DEFAULT SYSDATE, -- 주문날짜
   ORDER_STATUS NUMBER -- 배송 상태
);






DROP TABLE GOODS_ORDER;

--수정전
CREATE TABLE GOODS_ORDER(
   ORDER_NUM NUMBER,
   ORDER_GOODS_NUM   NUMBER,
   ORDER_GOODS_COUNT   NUMBER,
   ORDER_GOODS_NAME VARCHAR2(50),
   ORDER_GOODS_AMOUNT NUMBER,
   ORDER_GOODS_IMAGE VARCHAR2(50),
   ORDER_GOODS_PRICE NUMBER,
   ORDER_MEMBER_ID VARCHAR2(20),
   ORDER_RECEIVE_NAME VARCHAR2(20),
   ORDER_RECEIVE_ADDR1 VARCHAR2(70),
   ORDER_RECEIVE_ADDR2 VARCHAR2(70),
   ORDER_RECEIVE_PHONE VARCHAR2(13),
   ORDER_RECEIVE_MOBILE VARCHAR2(13),
   ORDER_MEMO VARCHAR2(3000),
   ORDER_SUM_MONEY NUMBER,
   ORDER_TRADE_TYPE VARCHAR2(20),
   ORDER_TRADE_DATE DATE DEFAULT SYSDATE,
   ORDER_TRADE_PAYER VARCHAR2(20),
   ORDER_DATE DATE DEFAULT SYSDATE,
   ORDER_STATUS NUMBER
);


drop table GOODS_ORDER
--수정후
CREATE TABLE GOODS_ORDER(
   ORDER_TRADENUM VARCHAR2(100),   --추가: 주문번호 S20210314_member.seq_member_ordernum
   ORDER_NUM NUMBER,
   ORDER_GOODS_NUM  NUMBER,
   ORDER_GOODS_NAME VARCHAR2(50),
   ORDER_GOODS_AMOUNT NUMBER, --전체 개수
   ORDER_GOODS_IMAGE VARCHAR2(50),
   ORDER_GOODS_PRICE NUMBER,
   ORDER_GOODS_COUNT NUMBER, --고객 주문 개수
   ORDER_MEMBER_SEQ NUMBER,      --추가: 고객 번호 member.seq
   ORDER_MEMBER_ORDERNUM NUMBER,   --추가: 고객의 주문건수
   ORDER_MEMBER_ID VARCHAR2(20),
   ORDER_RECEIVE_NAME VARCHAR2(20),
   ORDER_RECEIVE_ADDR1 VARCHAR2(70),
   ORDER_RECEIVE_ADDR2 VARCHAR2(70),
   ORDER_RECEIVE_PHONE VARCHAR2(13),
   ORDER_RECEIVE_MOBILE VARCHAR2(13),
   ORDER_MEMO VARCHAR2(3000),
   ORDER_SUM_MONEY NUMBER,
   ORDER_TRADE_TYPE VARCHAR2(20),
   ORDER_TRADE_DATE DATE DEFAULT SYSDATE,
   ORDER_TRADE_PAYER VARCHAR2(20),
   ORDER_DATE DATE DEFAULT SYSDATE,
   ORDER_STATUS NUMBER
);





INSERT INTO GOODS_ORDER(
	ORDER_TRADENUM, --추가
    ORDER_NUM,
    ORDER_GOODS_NUM,
    ORDER_GOODS_NAME,
    ORDER_GOODS_AMOUNT, --전체 개수
    ORDER_GOODS_IMAGE,
    ORDER_GOODS_PRICE, 
    ORDER_GOODS_COUNT, --고객 주문 개수
    ORDER_MEMBER_SEQ,      --추가: 고객 번호 member.seq
    ORDER_MEMBER_ORDERNUM,   --추가: 고객의 주문건수
    ORDER_MEMBER_ID,
    ORDER_RECEIVE_NAME,
    ORDER_RECEIVE_ADDR1,
    ORDER_RECEIVE_ADDR2,
    ORDER_RECEIVE_PHONE,
    ORDER_RECEIVE_MOBILE,
    ORDER_MEMO,
    ORDER_SUM_MONEY,
    ORDER_TRADE_TYPE,
    ORDER_TRADE_PAYER,
    ORDER_STATUS
)
VALUES('12345',1,3,'과자',30,'sinra.png',1200,5,1,2,'aa','나희','서울시','종로구','02454654','010245684','안녕',5000,'직배송','신한은행',3);


INSERT INTO GOODS_ORDER(
	ORDER_TRADENUM, --추가
    ORDER_NUM,
    ORDER_GOODS_NUM,
    ORDER_GOODS_NAME,
    ORDER_GOODS_AMOUNT, --전체 개수
    ORDER_GOODS_IMAGE,
    ORDER_GOODS_PRICE, 
    ORDER_GOODS_COUNT, --고객 주문 개수
    ORDER_MEMBER_SEQ,      --추가: 고객 번호 member.seq
    ORDER_MEMBER_ORDERNUM,   --추가: 고객의 주문건수
    ORDER_MEMBER_ID,
    ORDER_RECEIVE_NAME,
    ORDER_RECEIVE_ADDR1,
    ORDER_RECEIVE_ADDR2,
    ORDER_RECEIVE_PHONE,
    ORDER_RECEIVE_MOBILE,
    ORDER_MEMO,
    ORDER_SUM_MONEY,
    ORDER_TRADE_TYPE,
    ORDER_TRADE_PAYER,
    ORDER_STATUS
)
VALUES('678910',2,3,'과자',30,'sinra.png',1000,3,2,2,'bb','나라','서울시','종로구','02454654','010245684','안녕',5000,'직배송','신한은행',3);



